version: 2.1

jobs:
  build-and-test:
    docker:
      - image: "cimg/python:3.10.2"
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Script
          command: python ./script.py


  deploy-to-beta:
    docker:
      - image: "cimg/python:3.10.2"
    steps:
      - checkout
      - run:
          name: Deploy to Beta
          command: |
            aws s3 cp index.html s3://codebuild-beta/index.html

  deploy-to-prod:
    docker:
      - image: "cimg/python:3.10.2"
    steps:
      - checkout
      - run:
          name: Deploy to Prod
          command: |
            aws s3 cp index.html s3://codebuild-prod515/index.html

workflows:
  workflow:
    jobs:
      - build-and-test
      - deploy-to-beta:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - beta
      - deploy-to-prod:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
     