version: 2.1

jobs:
  build-and-test:
    docker:
      - image: "cimg/python:3.10.2"
    steps:
      - checkout

      - awscli/install

      - run:
          name: Install Python Packages
          command: |
            sudo apt-get update && sudo apt-get install -y python3-pip
            pip install boto3

      - run:
          name: Run Script
          command: python script.py

  deploy-to-beta:
    docker:
      - image: "cimg/python:3.10.2"
    steps:
      - checkout
      - awscli/install
      - run:
          name: Deploy to Beta
          command: |
            aws s3 cp index.html s3://codebuild-beta/index.html

  deploy-to-prod:
    docker:
      - image: "cimg/python:3.10.2"
    steps:
      - checkout
      - awscli/install
      - run:
          name: Deploy to Prod
          command: |
            aws s3 cp index.html s3://codebuild-prod515/index.html


  example:
    docker:
      - image: "cimg/python:3.10.2"
    steps:
      - checkout
      - awscli/install
      - run:
          name: Example Job
          command: |
            echo "This is an example job, replace this with your own commands"

workflows:
  workflow:
    jobs:
      - build-and-test
      - deploy-to-beta:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - beta
      - deploy-to-prod:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
      - example:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - feature/*
