version: 2.1

jobs:
  build-and-test:
    docker:
      - image: "cimg/python:3.10.2"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run CF Script
          command: python run_cf_template.py

  deploy-to-test:
    docker:
      - image: "amazon/aws-cli:latest"
    steps:
      - run:
          name: Deploy to Test
          command: |
            aws s3 cp index.html s3://codebuild-beta/index.html

  deploy-to-prod:
    docker:
      - image: "amazon/aws-cli:latest"
    steps:
      - run:
          name: Deploy to Prod
          command: |
            aws s3 cp index.html s3://codebuild-prod515/index.html

workflows:
  sample:
    jobs:
      - build-and-test
      - deploy-to-test:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - develop
      - deploy-to-prod:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
