version: 2.1

jobs:

      - deploy_beta:
          requires:
            - hold
      - pre_prod_hold:
          type: approval
          requires:
            - deploy_beta
      - deploy_prod:
          requires:
            - pre_prod_hold
          filters:
            branches:
              only:
                - master